### ISSUE TITLE
Can't Install Bower?

### ISSUE THREAD

**Issue by jesse9212** [scotch-io/scotch-box#186]
```
vagrant@scotchbox:~$ npm install -g gulp bower
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "gulp" "bower"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/npm-debug.log
```

Any ideas? Thanks for the help.
jesse9212

Had to add 127.0.0.1 in windows hosts file to fix the network issue.

Had to run the following command in ssh first before otherwise got errors when installing npm install -g gulp bower

sudo su -

Stuck on this now after running
```
bower install

bower ENOTFOUND Request to https://bower.herokuapp.com/packages/bootstrap-sass failed: getaddrinfo ENOTFOUND bower.herokuapp.com bower.herokuapp.com:443
```

Got past the error by sharing my ethernet adapter with the virtualbox host-only adapter and checking the boxes for HTTP&HTTPS:
[http://i.imgur.com/MKuQkMD.png](http://i.imgur.com/MKuQkMD.png)

Now getting this error:
```

/usr/local/lib/node_modules/bower/lib/node_modules/update-notifier/node_modules/configstore/index.js:53
                                throw err;
                                ^

Error: EACCES: permission denied, open '/home/vagrant/.config/configstore/update-notifier-bower.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/lib/node_modules/update-notifier/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/update-notifier/node_modules/configstore/index.js:27:44)
    at new UpdateNotifier (/usr/local/lib/node_modules/bower/lib/node_modules/update-notifier/index.js:35:17)
    at module.exports (/usr/local/lib/node_modules/bower/lib/node_modules/update-notifier/index.js:120:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:140:20)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

If I use sudo or --allow-root option or --allow-root I get the same error.

**Comment by ncerminara** [comment]
Did you figure this out? Seems to be a network issue vs Scotch Box specific

**Comment by ASidlinskiy** [comment]
Hi there, 

I'm encountering similar permission issue and not sure how to resolve it.

Here's the error I get.
```
vagrant@scotchbox:/var/www/public/wp-content/themes/sage$ bower install
/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:54
                                throw err;
                                ^

Error: EACCES: permission denied, open '/home/vagrant/.config/configstore/bower-github.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

I also like jesse9212 tried running `sudo bower install` command and it would give me additional errors shown below.

```
vagrant@scotchbox:/var/www/public/wp-content/themes/sage$ sudo bower install --alow-root
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
```

**Comment by basz** [comment]
alow-root is a typo
