### ISSUE TITLE
Browser-sync working quickly

### ISSUE THREAD

**Issue by familyyy** [scotch-io/scotch-box#265]
Hi
Thank you for the box.

I have:
- macOS Sierra 10.12
- brew cask install vagrant
- scotch-box
- my folder "myproject"
- `config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]`

My actions:

```
vagrant up
vagrant ssh
cd /var/www/
npm install
gulp
```

Error:

```
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:860:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:339:9)
    at module.exports (/var/www/node_modules/opn/index.js:75:24)
    at Object.utils.open (/var/www/node_modules/browser-sync/lib/utils.js:183:23)
    at Object.utils.openBrowser (/var/www/node_modules/browser-sync/lib/utils.js:164:23)
    at EventEmitter.events.service:running (/var/www/node_modules/browser-sync/lib/internal-events.js:45:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at /var/www/node_modules/browser-sync/lib/browser-sync.js:260:19
    at /var/www/node_modules/browser-sync/lib/utils.js:278:25
    at executeTask (/var/www/node_modules/browser-sync/lib/browser-sync.js:170:13)
    at Object.module.exports.initUserPlugins [as fn] (/var/www/node_modules/browser-sync/lib/async.js:317:9)
    at /var/www/node_modules/browser-sync/lib/browser-sync.js:149:14
    at iterate (/var/www/node_modules/browser-sync/lib/utils.js:271:13)
    at /var/www/node_modules/browser-sync/lib/utils.js:280:25
```

ok

changed
I comment out: `config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]`
Active:  `config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }`

```
vagrant reload
vagrant ssh
cd /var/www/
gulp
```

It's worked, but file update is very slow

ok
changed nfs line: `config.vm.synced_folder ".", "/var/www", :nfs => true, :mount_options => ["actimeo=1"]`

it's done! The browser-sync working quickly

**Comment by whatnickcodes** [comment]
Nice! Going to add this to the docs. You're best bet though is to run from the host and not the VM if you can. Especially if you're on Mac
