### ISSUE TITLE
NPM & Bower Broken.

### ISSUE THREAD

**Issue by Blindmikey** [scotch-io/scotch-box#317]
`npm -v` outputs
```
module.js:487
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:40:20
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/write-file-atomic/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

Same with `bower -v`.

**Comment by Blindmikey** [comment]
Found the following in the vagrant file:

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

This could be the issue. Investigating.

**Comment by whatnickcodes** [comment]
I think it's just you need `sudo` in the free version

**Comment by Blindmikey** [comment]
removing the custom provisioning lines outlined above seemed to fix the issue.
